name: Generate Snake Animation

on:
  schedule:
    # Runs at 5:00 UTC every day
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: Dungha125  # Thay "Dungha125" bằng username GitHub của bạn
          outputs: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
