name: Generate Snake Animation

on:
  schedule:
    # Thiết lập để chạy mỗi ngày lúc 5:00 UTC
    - cron: "0 5 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Lấy mã nguồn từ repository
      - uses: actions/checkout@v2
      # Sử dụng Platane/snk để tạo ra file snake.svg
      - uses: Platane/snk@v2
        with:
          github_user_name: Dungha125  # Thay "Dungha125" bằng tên tài khoản GitHub của bạn
          outputs: dist/snake.svg

      # Đẩy file snake.svg lên nhánh output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
